#! /bin/sh

#set -x

script=`basename $0`
if [ $# = 0 ]; then
	echo "Usage: $script [OPTIONS]... [PRJDIR]"
	echo "where OPTIONS can be:"
	echo "  -v       enable verbose output (default: false)"
	echo "  -s       set the date since you need hoc (default: today)"
	echo "  -t       set the date till you need hoc (default: today)"
	echo "  -f       set a filter on all files to calculate an hoc on specific files/dirs (default: none)"
	echo "and PRJDIR represents the (parent) project maven dir (default: current dir)"
	echo ""
	echo "Software required: git, grep and awk"
	exit 2
fi

directory="."
verbose=0
since=`date "+%Y-%m-%d"`
till=`date "+%Y-%m-%d"`
filter=""
while [ $# -gt 0 ]; do
	case $1 in
		-s) since="$2"
		    shift
		    ;;
		-t) till="$2"
		    shift
		    ;;
		-f) filter="$2"
		    shift
		    ;;
		-v) verbose=1
		    ;;
		*)  directory="$1"
		    ;;
	esac
	shift
done

if [ $verbose = 1 ]; then
	echo "Directory ...................: $directory"
	echo "Since .......................: $since"
	echo "Till ........................: $till"
	echo "Filter ......................: $filter"
fi

temp_file="/tmp/${script}_$$"
authors_file="/tmp/${script}_authors_$$"

pushd $directory > /dev/null

git --no-pager log --pretty=format:%an --date=iso --since="$since" --before="$till" | sort -u > $authors_file

IFS="
"
for author in `cat $authors_file`; do
	author_stat_file="/tmp/${script}_author_stat_$$"

	# extract stats for specific author...
	git --no-pager log --numstat --pretty=format:"%b" --no-merges --author="$author" --date=iso --ignore-space-change --ignore-all-space --ignore-submodules --find-copies-harder -M --diff-filter=ACDM --since="$since" --before="$till" > $author_stat_file

	# filter previous output...
	if [ "x$filter" != "x" ]; then
		grep "$filter" $author_stat_file > ${temp_file}
		cp ${temp_file} $author_stat_file
	fi

	hoc=`awk 'BEGIN { hoc = 0 } /^[0-9]/ { hoc = hoc + $1 + $2 } END { print hoc }' $author_stat_file`
	echo "$hoc\t$author"
done

popd > /dev/null
