#! /bin/sh

#set -x

script=`basename $0`
if [ $# = 0 ]; then
	echo "Usage: $script OPTIONS... PRJDIR"
	echo "where OPTIONS can be:"
	echo "  -v       enable verbose output"
	echo "and PRJDIR represents the (parent) project maven dir"
	exit 2
fi

directory="."
verbose=0
since=`date "+%Y-%m-%d"`
filter=""
while [ $# -gt 0 ]; do
	case $1 in
		-s) since="$2"
		    shift
		    ;;
		-f) filter="$2"
		    shift
		    ;;
		-v) verbose=1
		    ;;
		*)  directory="$1"
		    ;;
	esac
	shift
done

if [ $verbose = 1 ]; then
	echo "Directory ...................: $directory"
	echo "Since .......................: $since"
	echo "Filter ......................: $filter"
fi

temp_file="/tmp/${script}_$$"
authors_file="/tmp/${script}_authors_$$"

pushd $directory > /dev/null

git --no-pager log --pretty=format:%an --date=iso --since="$since" | sort -u > $authors_file

IFS="
"
for author in `cat $authors_file`; do
	author_stat_file="/tmp/${script}_author_stat_$$"

	# extract stats for specific author...
	git --no-pager log --numstat --pretty=format:"%b" --no-merges --author="$author" --date=iso --since="$since" > $author_stat_file

	# filter previous output...
	if [ "x$filter" != "x" ]; then
		grep "$filter" $author_stat_file > ${temp_file}
		cp ${temp_file} $author_stat_file
	fi

	hoc=`awk '/^[0-9]/ { hoc = hoc + $1 + $2 } END { print hoc }' $author_stat_file`
	if [ "x$hoc" != "x" ]; then
		echo "$hoc $author"
	fi
done

popd > /dev/null
